import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Fordel - No Talk, Only Code",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/fordel-logo.png" type="image/x-icon" />
      </head>
      <body>{children}</body>
    </html>
  );
}